### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Dhaulagiri** [heroku/ember-js-getting-started#1]
Outstanding items:
- [x] Update landing page with links to dev center articles
- [x] Add logo to landing page
- [x] Vet overall content of landing page
- [x] Create app.json for button deploys
